<?php
$title = 'Añadir Nuevo Usuario';
$this->headTitle($title);
?>
<div class='panel panel-info'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

<?php

$form->setAttribute('action', $this->url('usuario', array('action' => 'add')));
$form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<?php foreach($form as $element): ?>
    <div class="form-group">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
        ?>
    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>

