<?php
use Zend\Mvc\Controller\Plugin\FlashMessenger;

$title = 'Actualizar Password';
$this->headTitle($title);

?>

<?php echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_INFO, array('alert','alert-info')); ?>
<?php echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR, array('alert','alert-danger')); ?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
</div>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'usuario',
    array(
        'action' => 'cambiarpass',
        'id'     => $this->id,
    )
));

$form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>

<?php foreach($form as $element): ?>
    <?php
    if ($element->getName() == 'submit') {
        echo $this->formElement($element);
        continue;
    }
    ?>
    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);  
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
        ?>
    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>