<?php

$title = 'Editar Password';
$this->headTitle($title);

?>

<div class='panel panel-warning'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
</div>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'usuario',
    array(
        'action' => 'editpass',
        'id'     => $this->id,
    )
));

$form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<?php foreach($form as $element): ?>
    <?php if($element->getName() != 'password' && $element->getName() != 'submit') continue; ?>
    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);  
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
            
            if($element->getName() == 'submit') {
                echo ' <a class="btn btn-lg btn-danger" href="' . $this->url('usuario', array('action' => 'edit', 'id' => $this->id)) . '">Cancelar</a>';
            }
        ?>
    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>
