 <?php
 // module/Album/view/album/album/edit.phtml:
use Centro\Util\CatalogoValor as Catalogo;


 $title = 'Editar Usuario';
 $this->headTitle($title);
 ?>
 <div class='panel panel-warning'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'usuario',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); $usuarioestandar = false; ?>
<?php foreach($form as $element): ?>
    <?php 
            if($element->getValue() == Catalogo::ESTANDAR){
                $usuarioestandar = true;
                continue;
                //$element->setAttributes(array('disabled' => 'disabled'));
            }
            
            if($usuarioestandar){
                switch ($element->getName()){
                    case "usuario":
                    $element->setAttributes(array('disabled' => 'disabled'));
                    break;
                    case "pais":
                    $element->setAttributes(array('disabled' => 'disabled'));
                    break;
                }
            }
            
    ?>
    <div class="form-group">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);  
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
        ?>
    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>

<div>
    <?php
        if($usuarioestandar){
            echo $this->partial("partial/edit/centros.phtml", array('centros'=>$this->centros));
        }
    ?>
</div>