 <?php
 // module/Album/view/album/album/edit.phtml:

 $title = 'Editar Usuario';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'usuario',
     array(
         'action' => 'edit',
         'id'     => $this->id,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('tipo'));
 echo $this->formRow($form->get('usuario'));
 echo $this->formRow($form->get('password'));
 echo $this->formRow($form->get('email'));
 echo $this->formRow($form->get('pais'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();