<?php
use Zend\Mvc\Controller\Plugin\FlashMessenger;

$title = 'Ingreso';
$this->headTitle($title);

?>

<?php echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR, array('alert','alert-warning')); ?>

<div class="col-md-4 col-md-offset-4">
    <div class="login-panel panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">RELACIGER</h3>
        </div>
        <div class="panel-body">
            <div class="row">
            <?php echo $this->form()->openTag($form); ?>
            <?php foreach($form as $element): ?>
                <div class="form-group">
                    <label class="control-label"><?php echo $element->getLabel() ?></label>
                    <?php
                        echo $this->formElement($element);
                        if($this->formElementErrors($element)){
                            echo $this->formElementErrors()
                                    ->setMessageOpenFormat('<p class="help-block">')
                                    ->setMessageSeparatorString('</p><p class="help-block">')
                                    ->setMessageCloseString('</p>')
                                    ->render($element);
                        }
                    ?>
                </div>
            <?php endforeach; ?>
            <?php echo $this->form()->closeTag(); ?>
            </div>
        </div>
    </div>
</div>
    

