<?php
// module/Album/view/album/album/edit.phtml:
use Centro\Util\CatalogoValor as Catalogo;
use Zend\Mvc\Controller\Plugin\FlashMessenger;

$title = 'Perfil de Usuario';
$this->headTitle($title);
?>

<?php 
echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_INFO, array('alert','alert-info')); 
echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR, array('alert','alert-danger')); 
?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
</div>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'usuario',
    array(
        'action' => 'perfil',
        'id'     => $this->id,
    )
));
$form->prepare();

$usuarioestandar = false;
if($tipoUsuario == Catalogo::ESTANDAR) {
    $usuarioestandar = true;
}

?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<?php foreach($form as $element): ?>
    <?php
        if ($element->getName() == 'submit' || $element->getName()=='sbtcancelar') {
            echo $this->formElement($element);
            continue;
            //echo ' <a class="btn btn-lg btn-info" href="' . $this->url('usuario', array('action' => 'editpass', 'id' => $this->id)) . '">Cancelar</a>';
    }
        
        
        
    ?>
    <?php 
        if($element->getName() == 'tipo'){
            $element->setAttributes(array('disabled' => 'disabled'));
        }
        
        if($usuarioestandar){
            switch ($element->getName()){
                case "usuario":
                $element->setAttributes(array('readonly' => 'true'));
                break;
                case "pais":
                $element->setAttributes(array('readonly' => 'true'));
                break;
            }
        }
        
        if($element->getName() == 'password') continue;
            
    ?>
    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);  
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
            
            if ($element->getName() == 'usuario') {
                echo '<a class="btn btn-sm btn-warning" href="' . $this->url('usuario', array('action' => 'cambiarpass', 'id' => $this->id)) . '">Actualizar Password</a>';
            }
        ?>
    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>
