<?php
// module/Album/view/album/album/edit.phtml:
use Centro\Util\CatalogoValor as Catalogo;

$title = 'Perfil de Usuario';
$this->headTitle($title);
?>

<div class='panel panel-info'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
</div>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'usuario',
    array(
        'action' => 'perfil',
        'id'     => $this->id,
    )
));
$form->prepare();

$usuarioestandar = false;
if($tipoUsuario == Catalogo::ESTANDAR) {
    $usuarioestandar = true;
}

?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<?php foreach($form as $element): ?>
    <?php 
        if($element->getName() == 'tipo'){
            $element->setAttributes(array('disabled' => 'disabled'));
        }
        
        if($usuarioestandar){
            switch ($element->getName()){
                case "usuario":
                $element->setAttributes(array('readonly' => 'true'));
                break;
                case "pais":
                $element->setAttributes(array('readonly' => 'true'));
                break;
            }
        }
            
    ?>
    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);  
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
        ?>
    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>
