

 <?php
 $title = 'Añadir Nuevo Centro';
 $this->headTitle($title);
 ?>
<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
 </div>
 <?php
 $form->setAttribute('action', $this->url('centro', array('action' => 'add')));
 $form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nombre')) . "<br>";
echo $this->formRow($form->get('pais')). "<br>";
echo $this->formRow($form->get('siglas')). "<br>";
echo $this->formRow($form->get('sitio_web')). "<br>"; 
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();