<?php

 $title = 'Eliminar centro';
 $this->headTitle($title);
 ?>
 <div class='panel panel-danger'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

 <p>¿Esta seguro de que desea eliminar el centro 
     <strong>'<?php echo $this->escapeHtml($centro->nombre) . ' (' . $this->escapeHtml($centro->siglas) .')'; ?>'</strong>, tipo 
     <strong>'<?php echo $this->escapeHtml($centro->tipo); ?>'</strong>?
 </p>
 <?php
 $url = $this->url('centro', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $centro->id; ?>" />
     <input class="btn btn-success btn-lg" type="submit" name="del" value="Si" />
     <input class="btn btn-danger btn-lg" type="submit" name="del" value="No" />
 </div>
 </form>