 <?php
//"module/Centro/view/centro/centro/index.phtml"

 $title = 'Mis Centros';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('centro', array('action'=>'add'));?>">Agregar Nuevo Centro</a>
 </p>

 <table class="table table-striped">
 <tr>
     <th>ID</th>
     <th>Tipo</th>
     <th>Nombre</th>
     <th>Siglas</th>
     <th>Pais</th>
     <th>Sitio Web</th>
     <th>Direccion</th>
     <th>Telefono</th>
     <th>URL Imagen</th>
     <th>&nbsp;</th>
 </tr>
 
 <?php foreach ($centros as $centro) : ?>
 <?php $this->placeholder('foo')->bar[$centro->id] = $centro->siglas ?>
 <tr>
     <td><?php echo $this->escapeHtml($centro->id);?></td>
     <td><?php echo $this->escapeHtml($centro->tipo);?></td>
     <td><?php echo $this->escapeHtml($centro->nombre);?></td>
     <td><?php echo $this->escapeHtml($centro->siglas);?></td>
     <td><?php echo $this->escapeHtml($centro->pais);?></td>
     <td><?php echo $this->escapeHtml($centro->sitio_web);?></td>
     <td><?php echo $this->escapeHtml($centro->direccion);?></td>
     <td><?php echo $this->escapeHtml($centro->telefono);?></td>
     <td><?php echo $this->escapeHtml($centro->url_imagen);?></td>
     <td>
         <a href="<?php echo $this->url('centro',
             array('action'=>'edit', 'id' => $centro->id));?>">Editar</a>
         <a href="<?php echo $this->url('centro',
             array('action'=>'delete', 'id' => $centro->id));?>">Eliminar</a>
     </td>
 </tr>
  <?php endforeach; ?>
 </table>