<?php
use Zend\Mvc\Controller\Plugin\FlashMessenger;
 
$title = 'RELACIGER';
$this->headTitle($title);

?>
 
<?php echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_SUCCESS, array('alert','alert-success')); ?>
<?php echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_INFO, array('alert','alert-info')); ?>
<?php echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR, array('alert','alert-danger')); ?>

 <div class='jumbotron'>
    <h2>Gestor de contenido - App RELACIGER</h2>
    <p>
        Gestor de contenido de la aplicaci&oacute;n para dispositivos m&oacute;viles de la
        Red Latinoamericana de Centros de Informaci&oacute;n en Gesti&oacute;n del Riesgo de Desastres
    </p>
    <p>
    <ul>
        <li><a href="http://desastres.usac.edu.gt/content/app-relaciger" target="_blank"><i class="fa fa-mobile-phone fa-fw"></i>Informaci&oacute;n General - App Relaciger para m&oacute;viles</a></li>
        <li><a href="https://play.google.com/store/apps/details?id=dev.relaciger.apprelaciger&hl=es" target="_blank"><i class="fa fa-android fa-fw"></i> Perfil Google Play</a></li>
        <li><a href="https://itunes.apple.com/us/app/app-relaciger/id893471515?l=es&ls=1&mt=8" target="_blank"><i class="fa fa-apple fa-fw"></i> Perfil App Store</a></li>
        <li><a href="http://desastres.usac.edu.gt/sites/default/files/pictures/relaciger/manual_de_usuario_app_relaciger_web.pdf" target="_blank"><i class="fa fa-file-pdf-o fa-fw"></i> Manual de usuario</a></li>
    </ul>
    </p>
</div>