 <?php
 use Zend\Mvc\Controller\Plugin\FlashMessenger;
 
 $title = "RELACIGER - Informacion General";
 $this->headTitle($title);
 ?>

<?php 
echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_INFO, array('alert','alert-info')); 
echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_ERROR, array('alert','alert-danger')); 
?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>

<?php
$form->setAttribute('action', $this->url('centro', array('action' => 'relaciger')));
$form->setAttribute('class', 'col-lg-12');
$form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<?php foreach($form as $element): ?>
    <?php
        if ($element->getName() == 'submit') {
            echo $this->formElement($element);
            continue;
            //echo ' <a class="btn btn-lg btn-info" href="' . $this->url('usuario', array('action' => 'editpass', 'id' => $this->id)) . '">Cancelar</a>';
        }
    ?>
    <?php if($element->getName()== 'id' ||
            $element->getName()== 'nombre' ||
            $element->getName()== 'siglas' ||
            $element->getName()== 'sitio_web' ||
            $element->getName()== 'mision' || 
            $element->getName()== 'vision' || 
            $element->getName()== 'descripcion' || 
            $element->getName()== 'submit') { 
        
    ?>
    <div class="form-group <?php if($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
            if($element->getName() != 'id' &&
                    $element->getName() != 'nombre' &&
                    $element->getName() != 'siglas' &&
                    $element->getName() != 'sitio_web' &&
                    $element->getName() != 'submit') {
                
                $nombre = $element->getName();
                //var_dump($nombre);
                $this->QuCKEditor(
                    $nombre,
                    array(
                        'width' => "100%",
                        'height' => "150",
                        'uiColor' => '#FFFFFF',
                    )
                );
            }
        ?>
    </div>
    <?php  } ?>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>