 <?php
 $title = 'Informacion General - RELACIGER';
 $this->headTitle($title);
 ?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>

<?php
$form->setAttribute('action', $this->url('centro', array('action' => 'relaciger')));
$form->setAttribute('class', 'col-lg-12');
$form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<?php foreach($form as $element): ?>
    <?php if($element->getName()== 'id' ||
            $element->getName()== 'nombre' ||
            $element->getName()== 'siglas' ||
            $element->getName()== 'sitio_web' ||
            $element->getName()== 'mision' || 
            $element->getName()== 'vision' || 
            $element->getName()== 'descripcion' || 
            $element->getName()== 'submit') { 
        
        if($element->getName() == 'nombre' || $element->getName() == 'siglas' || $element->getName() == 'sitio_web') {
            $element->setAttributes(array('readonly' => 'true'));
        }
    ?>
    <div class="form-group">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
            if($element->getName() != 'id' &&
                    $element->getName() != 'nombre' &&
                    $element->getName() != 'siglas' &&
                    $element->getName() != 'sitio_web' &&
                    $element->getName() != 'submit') {
                
                $nombre = $element->getName();
                //var_dump($nombre);
                $this->QuCKEditor(
                    $nombre,
                    array(
                        'width' => "100%",
                        'height' => "150",
                        'uiColor' => '#FFFFFF',
                    )
                );
            }
        ?>
    </div>
    <?php  } ?>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>