<?php
$title ='Contacto - '  . $centro->siglas ;
$this->headTitle($title);
?>
<div class='panel panel-info'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

 <?php
$form->setAttribute('action', $this->url('contacto', array('action' => 'add', 'id'=>$centro->id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('centro_id')->setValue($centro->id));
echo $this->formRow($form->get('nombre')). "<br>";
echo $this->formRow($form->get('email')). "<br>";
echo $this->formRow($form->get('telefono')). "<br>";
echo $this->formRow($form->get('puesto')). "<br>"; 
echo $this->formSubmit($form->get('submit')->setValue('Agregar'));
echo $this->form()->closeTag();

?>