<?php
$title ="Edicion de Contacto". " - " . $centro->siglas ;
$this->headTitle($title);
?>

<div class='panel panel-warning'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
</div>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url('contacto', array('action' => 'edit', 'id' => $contacto->id)));
$form->setAttribute('class', 'col-md-6');

$form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<?php foreach($form as $element): ?>
    
    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            if($element->getName() == 'centro_id') $element->setValue($centro->id);
            echo $this->formElement($element);
            
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
        ?>
    </div>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>