 <?php

 $title = 'Contactos';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('contacto', array('action'=>'add'));?>">Agregar Nuevo Contacto</a>
 </p>

 <table class="table table-striped">
 <tr>
     <th>Id</th>
     <th>Nombre</th>
     <th>Email</th>
     <th>Telefono</th>
     <th>Puesto</th>
     <th>&nbsp;</th>
 </tr>
 
 <?php foreach($contactos as $contacto) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($contacto->id);?></td>
     <td><?php echo $this->escapeHtml($contacto->nombre);?></td>
     <td><?php echo $this->escapeHtml($contacto->email);?></td>
     <td><?php echo $this->escapeHtml($contacto->telefono);?></td>
     <td><?php echo $this->escapeHtml($contacto->puesto);?></td>
     <td>
         <a href="<?php echo $this->url('contacto',
             array('action'=>'edit', 'id' => $contacto->id));?>">Editar</a>
         <a href="<?php echo $this->url('contacto',
             array('action'=>'delete', 'id' => $contacto->id));?>">Eliminar</a>
     </td>
 </tr>
  <?php endforeach; ?>
 </table>