 <?php
 use Zend\Mvc\Controller\Plugin\FlashMessenger;
 
 $title =$centro->siglas . " - Contactos" ;
 $this->headTitle($title);
 ?>

<?php echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_INFO, array('alert','alert-info')); ?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>

 <p>
     <a class="btn btn-primary" href="<?php echo $this->url('contacto', array('action'=>'add', 'id'=>$centro->id));?>">Agregar Contacto</a>
 </p>

 <table class="table table-hover">
     <thead>
         <tr class="active">
             <th>Id</th>
             <th>Nombre</th>
             <th>Telefono</th>
             <th>Email</th>
             <th>Puesto</th>
             <th>Acciones</th>
         </tr>
     </thead>
     <tbody>
        <?php foreach ($contactos as $contacto): ?>
        <tr>
            <td><?php echo $this->escapeHtml($contacto->id);?></td>
            <td><?php echo $this->escapeHtml($contacto->nombre);?></td>
            <td><?php echo $this->escapeHtml($contacto->telefono);?></td>
            <td><?php echo $this->escapeHtml($contacto->email);?></td>
            <td><?php echo $this->escapeHtml($contacto->puesto);?></td>
            <td>
               <a class="btn btn-lg btn-warning" href="<?php echo $this->url('contacto',
                   array('action'=>'edit', 'id' => $contacto->id));?>">Editar</a>
               <a class="btn btn-lg btn-danger" href="<?php echo $this->url('contacto',
                   array('action'=>'delete', 'id' => $contacto->id));?>">Eliminar</a>
            </td>
        </tr>
        <?php endforeach; ?>
     </tbody>
 </table>