 <?php
 $title =$centro->siglas . "- Contactos " ;
 $this->headTitle($title);
 ?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>

 <p>
     <a href="<?php echo $this->url('contacto', array('action'=>'add', 'id'=>$centro->id));?>">Agregar Contacto</a>
 </p>

 <table class="table table-striped">
 <tr>
     <th>Id</th>
     <th>Nombre</th>
     <th>Telefono</th>
     <th>Email</th>
     <th>Puesto</th>
     <th>Centro_ID</th>
     <th>Acciones</th>
 </tr>
 <?php 

 foreach ($contactos as $contacto) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($contacto->id);?></td>
     <td><?php echo $this->escapeHtml($contacto->nombre);?></td>
     <td><?php echo $this->escapeHtml($contacto->telefono);?></td>
     <td><?php echo $this->escapeHtml($contacto->email);?></td>
     <td><?php echo $this->escapeHtml($contacto->puesto);?></td>
     <td><?php echo $this->escapeHtml($contacto->centro_id);?></td>
     <td>
         
         <a class="btn btn-lg btn-warning" href="<?php echo $this->url('contacto',
             array('action'=>'edit', 'id' => $contacto->id));?>">Editar</a>
         
         <form method="POST" action=" <?php echo $this->url('contacto',array('action'=>'listar')); ?> ">
             <input type="hidden" name= 'canal' value="<?php echo $canal->id; ?>" />
             <input class="btn btn-lg btn-danger" type='submit' value='Eliminar' />
         </form>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>