 <?php
//"module/Centro/view/centro/centro/index.phtml"

 $title = 'Usuarios';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('user', array('action'=>'add'));?>">Agregar Nuevo Usuario</a>
 </p>
 
 <table class="table table-striped">
 <tr>
     <th>Id</th>
     <th>Tipo</th>
     <th>Usuario</th>
     <th>Password</th>
     <th>Pais</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($usuarios as $usuario) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($usuario->id);?></td>
     <td><?php echo $this->escapeHtml($usuario->tipo);?></td>
     <td><?php echo $this->escapeHtml($usuario->usuario);?></td>
     <td><?php echo $this->escapeHtml($usuario->pais);?></td>
     <td>
         <a href="<?php echo $this->url('user',
             array('action'=>'edit', 'id' => $usuario->id));?>">Editar</a>
         <a href="<?php echo $this->url('user',
             array('action'=>'delete', 'id' => $usuario->id));?>">Eliminar</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>