<?php
$title = $centro->siglas . " - Gestion  de Usuarios" ;
$this->headTitle($title);
?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>


<?php if(sizeof($usuarios)>0):?>
<form method="POST" action="<?php echo $this->url('usuariocentro', array('action' => 'find', 'id' => $centro->id)) ?>"
    <div>
      <select class='btn btn-lg btn-default' name="selectusuario">
              <?php foreach ($usuarios as $usuario): ?>
            <option value = '<?php echo $this->escapeHtml($usuario->id); ?>'><?php echo $this->escapeHtml($usuario->usuario); ?> </option>
        <?php endforeach; ?>
    </select>
        <input class = 'btn btn-lg btn-success' type='submit' value="Asignar usuario a <?php echo $centro->siglas ?>">
    </div>
</form>
<?php endif; ?>


<br>
<table class="table table-hover">
    <thead>
        <tr class="active">
            <th>Usuarios permitidos </th>
            <th>Centro</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
    <?php foreach ($usuarioscentros as $usuariocentro) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($usuariocentro->usuario_valor); ?></td>
            <td><?php echo $this->escapeHtml($usuariocentro->centro_valor); ?></td>
            <td>
                <a class="btn btn-lg btn-danger" href="<?php echo $this->url('usuariocentro', array('action' => 'delete', 'id' => $usuariocentro->id));
        ?>">Desasignar</a>
            </td>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>