<?php
$title =$canal->titulo . " - ". $centro->siglas ;
$this->headTitle($title);
?>
<div class='panel panel-info'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

 <?php
$form->setAttribute('action', $this->url('item', array('action' => 'add', 'id'=>$canal->id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('canal_id')->setValue($this->canal->id));
echo $this->formRow($form->get('titulo')). "<br>";
echo $this->formRow($form->get('enlace')). "<br>";
echo $this->formRow($form->get('descripcion')). "<br>"; 
echo $this->formSubmit($form->get('submit')->setValue('Agregar'));
echo $this->form()->closeTag();

?>