 <?php

$title =$canal->titulo . " - ". $centro->siglas ;
 $this->headTitle($title);
 ?>
 <div class='panel panel-warning'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'item',
     array(
         'action' => 'edit',
         'id'     => $item->id,
     )
 ));
 $form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<?php
echo $this->formHidden($form->get('id')->setValue($item->id));
echo $this->formHidden($form->get('canal_id')->setValue($canal->id));
echo $this->formRow($form->get('titulo')). "<br>";
echo $this->formRow($form->get('enlace')). "<br>";
echo $this->formRow($form->get('descripcion')). "<br>"; 
echo $this->formSubmit($form->get('submit')->setValue('Editar'));
echo $this->form()->closeTag();
?>
</div>