 <?php

$title = $centro->siglas . " - Editar Item (Canal Interno)";
 $this->headTitle($title);
 ?>
 <div class='panel panel-warning'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'item',
     array(
         'action' => 'edit',
         'id'     => $item->id,
     )
 ));
 $form->setAttribute('class', 'col-md-6');
 $form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
    <br>
    <?php foreach($form as $element): ?>
     <?php
        if ($element->getName() == 'submit') {
            echo $this->formElement($element);
            continue;
            //echo ' <a class="btn btn-lg btn-info" href="' . $this->url('usuario', array('action' => 'editpass', 'id' => $this->id)) . '">Cancelar</a>';
        }
    ?>
    <?php if($element->getName() == 'id' || $element->getName() == 'canal_id') {
        echo $this->formElement($element);
    } else {
    ?>
    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
        ?>
    </div>
    <?php } ?>
    <?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>
</div>