 <?php
//"module/Centro/view/centro/centro/index.phtml"

 $title = 'Items';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('item', array('action'=>'add'));?>">Agregar Nuevo Item</a>
 </p>

 <table class="table table-striped">
 <tr>
     <th>Id</th>
     <th>Titulo</th>
     <th>Enlace</th>
     <th>Descripcion</th>
     <th>Fecha de Publicacion</th>
     <th>Canal</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($items as $item) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($item->id);?></td>
     <td><?php echo $this->escapeHtml($item->titulo);?></td>
     <td><?php echo $this->escapeHtml($item->enlace);?></td>
     <td><?php echo $this->escapeHtml($item->descripcion);?></td>
     <td><?php echo $this->escapeHtml($item->fecha_publicacion);?></td>
     <td><?php echo $this->escapeHtml($item->canal_id);?></td>
     <td>
         <a href="<?php echo $this->url('canal',
             array('action'=>'edit', 'id' => $item->id));?>">Editar</a>
         <a href="<?php echo $this->url('canal',
             array('action'=>'delete', 'id' => $item->id));?>">Eliminar</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>