 <?php
//"module/Centro/view/centro/centro/index.phtml"

 $title =$canal->titulo . " - ". $centro->siglas ;
 $this->headTitle($title);
 ?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>


 <p>
     <a href="<?php echo $this->url('canal', array('action'=>'edit', 'id'=>$canal->id));?>">Configurar Canal Interno</a>
 </p>
 <p>
     <a href="<?php echo $this->url('item', array('action'=>'add', 'id'=>$canal->id));?>">Agregar Nuevo Item</a>
 </p>

 <table class="table table-striped">
 <tr>
     <th>Titulo</th>
     <th>Enlace</th>
     <th>Fecha de Publicacion</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($items as $item) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($item->titulo);?></td>
     <td><?php echo $this->escapeHtml($item->enlace);?></td>
     <td><?php echo $this->escapeHtml($item->fecha_publicacion);?></td>
     <td>
         
         <a class="btn btn-lg btn-warning" href="<?php echo $this->url('item',
             array('action'=>'edit', 'id' => $item->id));?>">Editar</a>
         
         <form method="POST" action=" <?php echo $this->url('item',array('action'=>'listar')); ?> ">
             <input type="hidden" name= 'item' value="<?php echo $item->id; ?>" />
             <input class="btn btn-lg btn-danger" type='submit' value='Eliminar' />
         </form>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>