<?php
use Centro\Util\CatalogoValor as Catalogo;

$title ='Canales - '  . $centro->siglas ;
$this->headTitle($title);
?>
<div class='panel panel-info'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

 <?php
$form->setAttribute('action', $this->url('canal', array('action' => 'add', 'id'=>$centro->id)));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('tipo')->setValue(Catalogo::EXTERNO));
echo $this->formHidden($form->get('centro_id')->setValue($centro->id));
echo $this->formHidden($form->get('secuencia')->setValue($secuencia));
echo $this->formRow($form->get('titulo')). "<br>";
echo $this->formRow($form->get('enlace')). "<br>";
echo $this->formRow($form->get('lenguaje')). "<br>";
echo $this->formRow($form->get('descripcion')). "<br>"; 
echo $this->formSubmit($form->get('submit')->setValue('Editar'));
echo $this->form()->closeTag();

?>