<?php

 $title = $centro->siglas . ' - Eliminar Canal'; 
 $this->headTitle($title);
 ?>

 <div class='panel panel-danger'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

 <p>¿Esta seguro que desea eliminar el Canal
     <strong>'<?php echo $this->escapeHtml($canal->titulo); ?>'</strong>, enlace 
     <strong>'<?php echo $this->escapeHtml($canal->enlace); ?>'</strong>?
 </p>
 <?php
 $url = $this->url('canal', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $canal->id; ?>" />
     <input class="btn btn-success btn-lg" type="submit" name="del" value="Si" />
     <input class="btn btn-danger btn-lg" type="submit" name="del" value="No" />
 </div>
 </form>