<?php

 $title = 'Eliminar Centro';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <p>Esta seguro de que desea eliminar un canal?
     '<?php echo $this->escapeHtml($canal->tipo); ?>' by
     '<?php echo $this->escapeHtml($canal->titulo); ?>'?
 </p>
 <?php
 $url = $this->url('canal', array(
     'action' => 'delete',
     'id'     => $this->id,
 ));
 ?>
 <form action="<?php echo $url; ?>" method="post">
 <div>
     <input type="hidden" name="id" value="<?php echo (int) $canal->id; ?>" />
     <input type="submit" name="del" value="Yes" />
     <input type="submit" name="del" value="No" />
 </div>
 </form>