 <?php
use Centro\Util\CatalogoValor as Catalogo;

$title ="Edicion de Canales". "-" . $centro->siglas ;
 $this->headTitle($title);
 ?>
 <div class='panel panel-warning'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
 </div>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'canal',
     array(
         'action' => 'edit',
         'id'     => $canal->id,
     )
 ));
 $form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<?php
echo $this->formHidden($form->get('id')->setValue($canal->id));
echo $this->formHidden($form->get('secuencia')->setValue($canal->secuencia));
echo $this->formHidden($form->get('centro_id')->setValue($centro->id));
echo $this->formHidden($form->get('tipo')->setValue(Catalogo::EXTERNO));
echo $this->formRow($form->get('titulo')). "<br>";
echo $this->formRow($form->get('enlace')). "<br>";
echo $this->formRow($form->get('lenguaje')). "<br>";
echo $this->formRow($form->get('descripcion')). "<br>"; 
echo $this->formSubmit($form->get('submit')->setValue('Editar'));
echo $this->form()->closeTag();
?>
</div>