 <?php
use Centro\Util\CatalogoValor as Catalogo;

$title ="Edicion de Canal". " - " . $centro->siglas ;
$this->headTitle($title);
?>
<div class='panel panel-warning'>
    <div class='panel-heading'>
        <h3><?php echo $this->escapeHtml($title); ?></h3>
    </div>
</div>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'canal',
    array(
        'action' => 'edit',
        'id'     => $canal->id,
    )
));
$form->setAttribute('class', 'col-md-6');
$form->prepare();
?>

<div class="row">
<?php echo $this->form()->openTag($form); ?>
<br>
<?php foreach($form as $element): ?>
    <?php 
    if($element->getName() == 'id' || 
            $element->getName() == 'centro_id' || 
            $element->getName() == 'secuencia' || 
            $element->getName() == 'tipo') {
            
        switch ($element->getName()){
            case 'centro_id':
                echo $this->formElement($element->setValue($centro->id));
                break;
            case 'secuencia':
                echo $this->formElement($element->setValue($canal->secuencia));
                break;
            case 'tipo':
                echo $this->formElement($element->setValue(Catalogo::EXTERNO));
                break;
            default:
                echo $this->formElement($element->setValue($canal->id));
        }
            
    } else {
    ?>
    <div class="form-group <?php if ($this->formElementErrors($element)) echo "has-error" ?>">
        <label class="control-label"><?php echo $element->getLabel() ?></label>
        <?php
            echo $this->formElement($element);
            if($this->formElementErrors($element)){
                echo $this->formElementErrors()
                        ->setMessageOpenFormat('<p class="help-block">')
                        ->setMessageSeparatorString('</p><p class="help-block">')
                        ->setMessageCloseString('</p>')
                        ->render($element);
            }
        ?>
    </div>
    <?php } ?>
<?php endforeach; ?>
<?php echo $this->form()->closeTag(); ?>    
</div>