<?php
use Centro\Util\CatalogoValor as Catalogo;

$title = $centro->siglas . ' - Canales RSS Externos' ;
$this->headTitle($title);
?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>
<br>

 <?php
 $form->setAttribute('action', $this->url('canal', array('action' => 'listar')));
 $form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formHidden($form->get('secuencia')->setValue($secuencia));
echo $this->formHidden($form->get('centro_id')->setValue($centro->id));
echo $this->formHidden($form->get('tipo')->setValue(Catalogo::EXTERNO));
echo $this->formRow($form->get('titulo')). "<br>";
echo $this->formRow($form->get('enlace')). "<br>";
echo $this->formRow($form->get('descripcion')). "<br>"; 
echo $this->formSubmit($form->get('submit')->setValue('Agregar'));
echo $this->form()->closeTag();

?>

<table class="table table-striped">
    <tr>
        <th>Id</th>
        <th>Secuencia</th>
        <th>Titulo</th>
        <th>Enlace</th>
        <th>Acciones</th>
    </tr>
    <?php foreach ($canales as $canal) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($canal->id); ?></td>
            <td><?php echo $this->escapeHtml($canal->secuencia); ?></td>
            <td><?php echo $this->escapeHtml($canal->titulo); ?></td>
            <td><?php echo $this->escapeHtml($canal->enlace); ?></td>
            <?php
             $form->setAttribute('action', $this->url('canal', array('action' => 'externo', 'accion'=>'del')));
             $form->prepare();
             echo $this->form()->openTag($form);
             echo $this->formHidden($form->get('id')->setValue($canal->id));
             echo $this->formHidden($form->get('secuencia')->setValue($canal->secuencia));
             echo $this->formHidden($form->get('centro_id')->setValue($centro->id));
             echo "<td>" . $this->formSubmit($form->get('submit')->setValue('Eliminar')). "</td>";
             echo $this->form()->closeTag();
            ?>
           
        </tr>
    <?php endforeach; ?>
</table>



