 <?php
//"module/Centro/view/centro/centro/index.phtml"

 $title = 'Mis canales';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('canal', array('action'=>'add'));?>">Agregar Nuevo Canal</a>
 </p>

 <table class="table table-striped">
 <tr>
     <th>Id</th>
     <th>Tipo</th>
     <th>Titulo</th>
     <th>Enlace</th>
     <th>Lenguaje</th>
     <th>Descripcion</th>
     <th>Centro</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($canales as $canal) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($canal->id);?></td>
     <td><?php echo $this->escapeHtml($canal->tipo);?></td>
     <td><?php echo $this->escapeHtml($canal->titulo);?></td>
     <td><?php echo $this->escapeHtml($canal->enlace);?></td>
     <td><?php echo $this->escapeHtml($canal->lenguaje);?></td>
     <td><?php echo $this->escapeHtml($canal->descripcion);?></td>
     <td><?php echo $this->escapeHtml($canal->centro_id);?></td>
     <td>
         <a href="<?php echo $this->url('canal',
             array('action'=>'edit', 'id' => $canal->id));?>">Editar</a>
         <a href="<?php echo $this->url('canal',
             array('action'=>'delete', 'id' => $canal->id));?>">Eliminar</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>