 <?php
 //"module/Centro/view/centro/centro/index.phtml"
 use Zend\Mvc\Controller\Plugin\FlashMessenger;
 
 $title =$centro->siglas . "- Canales Externos" ;
 $this->headTitle($title);
 ?>

<?php echo $this->flashMessenger()->render(FlashMessenger::NAMESPACE_INFO, array('alert','alert-info')); ?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>

 <p>
     <a class="btn btn-primary" href="<?php echo $this->url('canal', array('action'=>'add', 'id'=>$centro->id));?>">Agregar Canal RSS</a>
 </p>

 <table class="table table-hover">
     <thead>
         <tr class="active">
         <th>Secuencia</th>
         <th>Nombre</th>
         <th>Enlace</th>
         <th>Acciones</th>
         </tr>
     </thead>
     <tbody>
         <?php foreach ($canales as $canal) : ?>
         <tr>
             <td><?php echo $this->escapeHtml($canal->secuencia);?></td>
             <td><?php echo $this->escapeHtml($canal->titulo);?></td>
             <td><?php echo $this->escapeHtml($canal->enlace);?></td>
             <td>
                <a class="btn btn-lg btn-warning" href="<?php echo $this->url('canal',
                   array('action'=>'edit', 'id' => $canal->id));?>">Editar</a>
                <a class="btn btn-lg btn-danger" href="<?php echo $this->url('canal',
                   array('action'=>'delete', 'id' => $canal->id));?>">Eliminar</a>
             </td>
         </tr>
         <?php endforeach; ?>
     </tbody>
 </table>