 <?php
//"module/Centro/view/centro/centro/index.phtml"

 $title =$centro->siglas . "- Canales Externos" ;
 $this->headTitle($title);
 ?>

<div class='panel panel-primary'>
    <div class='panel-heading'>
        <h1><?php echo $this->escapeHtml($title); ?></h1>
    </div>
</div>

 <p>
     <a href="<?php echo $this->url('canal', array('action'=>'add', 'id'=>$centro->id));?>">Agregar Canal RSS</a>
 </p>

 <table class="table table-striped">
 <tr>
     <th>Id</th>
     <th>Secuencia</th>
     <th>Titulo</th>
     <th>Enlace</th>
     <th>&nbsp;</th>
 </tr>
 <?php 

 foreach ($canales as $canal) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($canal->id);?></td>
     <td><?php echo $this->escapeHtml($canal->secuencia);?></td>
     <td><?php echo $this->escapeHtml($canal->titulo);?></td>
     <td><?php echo $this->escapeHtml($canal->enlace);?></td>
     <td>
         
         <a class="btn btn-lg btn-warning" href="<?php echo $this->url('canal',
             array('action'=>'edit', 'id' => $canal->id));?>">Editar</a>
         
         <form method="POST" action=" <?php echo $this->url('canal',array('action'=>'listar')); ?> ">
             <input type="hidden" name= 'canal' value="<?php echo $canal->id; ?>" />
             <input class="btn btn-lg btn-danger" type='submit' value='Eliminar' />
         </form>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>